#!/bin/bash
# session-end.sh — Capture lessons before restarting agent session
# Usage: ./scripts/session-end.sh <agent>
#
# MUST run before restarting any agent session!

set -euo pipefail

AGENT="${1:-}"
if [ -z "$AGENT" ]; then
  echo "Usage: ./scripts/session-end.sh <agent>"
  echo "Example: ./scripts/session-end.sh MAX"
  exit 1
fi

AGENT_UPPER=$(echo "$AGENT" | tr '[:lower:]' '[:upper:]')
AGENT_LOWER=$(echo "$AGENT" | tr '[:upper:]' '[:lower:]')
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
EVOX_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SESSION_DIR="$EVOX_DIR/docs/sessions"
SESSION_FILE="$SESSION_DIR/${DATE}-${AGENT_LOWER}.md"

# Create sessions dir if needed
mkdir -p "$SESSION_DIR"

echo "📝 Capturing session for $AGENT_UPPER..."

# 1. Capture terminal output (last 100 lines)
TERMINAL_OUTPUT=$(tmux capture-pane -t "evox-$AGENT_LOWER" -p -S -100 2>/dev/null || echo "No terminal session")

# 2. Get recent activity from Convex
RECENT_ACTIVITY=$(curl -s "https://gregarious-elk-556.convex.site/status" 2>/dev/null | \
  jq -r ".recentActivity[] | select(.agentName==\"$AGENT_LOWER\") | \"- \(.description | .[0:80])\"" 2>/dev/null | head -5 || echo "- No activity logged")

# 3. Create session log
cat > "$SESSION_FILE" << EOF
# Session: $AGENT_UPPER — $DATE $TIME

## Activity This Session
$RECENT_ACTIVITY

## Terminal Output (last 100 lines)
\`\`\`
$TERMINAL_OUTPUT
\`\`\`

## Lessons Learned
<!-- AGENT: Fill this before restart! -->
1. **[Keyword]** — 
2. **[Keyword]** — 
3. **[Keyword]** — 

## Blockers Encountered
- 

## Handoff Notes (for next session)
- 

---
*Auto-generated by session-end.sh*
EOF

echo "✅ Session log created: $SESSION_FILE"

# 4. Ask agent for lessons (send to tmux)
echo "🤖 Asking $AGENT_UPPER for lessons..."
tmux send-keys -t "evox-$AGENT_LOWER" "BEFORE YOU END: Write 3 lessons learned this session to $SESSION_FILE. Format: 1. **Keyword** — explanation. Then say DONE." Enter 2>/dev/null || true

# 5. Post to Convex activity
curl -s -X POST "https://gregarious-elk-556.convex.site/logActivity" \
  -H "Content-Type: application/json" \
  -d "{
    \"agent\": \"$AGENT_LOWER\",
    \"action\": \"session_end\",
    \"description\": \"Session ended. Log: $SESSION_FILE\"
  }" 2>/dev/null || true

echo ""
echo "📋 Next steps:"
echo "   1. Wait for agent to fill lessons in $SESSION_FILE"
echo "   2. Review and move important lessons to docs/LESSONS.md"
echo "   3. Then restart: tmux kill-session -t evox-$AGENT_LOWER"
echo "   4. Start fresh: ./scripts/start-agent.sh $AGENT_LOWER"
